### PR TITLE
Creater chat Room

### PR DESCRIPTION
**Pull request by bitcoinamerica**
To com. with dev's

### CODE REVIEW

**Comment by bitcoinamerica** [comment]
Hey joe let me know when you see this

**Comment by LNOSRESEARCHER** [comment]
I see it

**Comment by bitcoinamerica** [comment]
cool here we can chat with one another

**Comment by LNOSRESEARCHER** [comment]
good

**Comment by LNOSRESEARCHER** [comment]
so if i wanted to research liquid at github would i go back to community 
and grab item or copy and bring back here

**Comment by LNOSRESEARCHER** [comment]
where would i search at is my ?

**Comment by bitcoinamerica** [comment]
top left of gethub or back track the download link from google to liquidity home page and they should have a link to there github

**Comment by LNOSRESEARCHER** [comment]
nice

**Comment by bitcoinamerica** [comment]
if you check out the projects tab and click LNOS you can see the things im working on

**Comment by bitcoinamerica** [comment]
uploaded the .iso and after uploading it tels me sry you cant upload a .iso try .zip it
lol

**Comment by bitcoinamerica** [comment]
are you trying to edit the readme.md or project?

**Comment by bitcoinamerica** [comment]
if it will let you fix it and you know your change is for the better, go ahead and fix it, if you want me to confirm it do a request i think

**Comment by bitcoinamerica** [comment]
and i see newest comments go to the bottom so keep that in mind as you search through the form and looking for the latest info

**Comment by LNOSRESEARCHER** [comment]
project

**Comment by bitcoinamerica** [comment]
dont mess with project right now im still uploading the .iso.zip but when i go to update the upload ill add the "DD" in it

**Comment by LNOSRESEARCHER** [comment]
i edit it already did not need DD.... needed , removed

**Comment by bitcoinamerica** [comment]
also in the readme.md file at the bottom we need all our nodes 1-6 channel address added to the bottom, if you want to

**Comment by LNOSRESEARCHER** [comment]
sorry

**Comment by bitcoinamerica** [comment]
dont know what format will make them look nice something like
# bitcoin america ln1
6447383822454545454545453632747584
# bitcoin america ln2
6447383822454545454545453632747584
# bitcoin america ln3
6447383822454545454545453632747584
ex.

**Comment by bitcoinamerica** [comment]
remember you can place a "#" do make it go bold

**Comment by LNOSRESEARCHER** [comment]
all that for the OS why putting bitcoin amer..... in there

**Comment by bitcoinamerica** [comment]
right its time for the name change 
# LNOS America LN1

**Comment by bitcoinamerica** [comment]
..........dont sound right
# LNOS America N1
N1= Node1
? what you think?

**Comment by LNOSRESEARCHER** [comment]
wheres 4,5,6,

**Comment by LNOSRESEARCHER** [comment]
need bitcoin in there

**Comment by bitcoinamerica** [comment]
can you explain you last comment they seam like random msgs?

**Comment by LNOSRESEARCHER** [comment]
Bitcoin America LN2

**Comment by LNOSRESEARCHER** [comment]
you gave me addresses for 1,2,3,

**Comment by LNOSRESEARCHER** [comment]
name needed the word Bitcoin in the line

**Comment by bitcoinamerica** [comment]
I have No problem staying with "Bitcoin America LN#"  or we can find something to go with "LNOS"

**Comment by LNOSRESEARCHER** [comment]
name dont matter i guess here

**Comment by LNOSRESEARCHER** [comment]
should be like 
Bitcoin America LNOS LN1 or
LNOS Bitcoin America NL2

**Comment by bitcoinamerica** [comment]
what about
# Bitcoin America LNOS-1
# Bitcoin America LNOS-2
# Bitcoin America LNOS-3
# Bitcoin America LNOS-4
# Bitcoin America LNOS5
# Bitcoin America LNOS6

**Comment by bitcoinamerica** [comment]
> what about
> # Bitcoin America LNOS-1
> # Bitcoin America LNOS-2
> # Bitcoin America LNOS-3
> 
> or
> # Bitcoin America LNOS4
> # Bitcoin America LNOS5
> # Bitcoin America LNOS6

i like the one with the -

**Comment by bitcoinamerica** [comment]
The First release of LNOS just uploaded to the Github release page for download.
Time to start work on the other OS's
sucks i go back to work Monday and wont have time to work on the project till next week but as of now its a fully functional LNOS

**Comment by LNOSRESEARCHER** [comment]
looks good DONE.

**Comment by bitcoinamerica** [comment]
We are up to 1000 views in just one day.
# Hi Every one welcome to the Release of LNOS
as you can see the dev's are hard at work just trying to just figure out a name, the Focus group is close to figuring one out.

**Comment by bitcoinamerica** [comment]
I second that motion for the name to become Bitcoin America LNOS-1

**Comment by LNOSRESEARCHER** [comment]
https://github.com/stratisproject/FederatedSidechains

**Comment by LNOSRESEARCHER** [comment]
it has been decided
Bitcoin America LNOS-1-6

**Comment by bitcoinamerica** [comment]
what is this?
https://github.com/stratisproject/FederatedSidechains

**Comment by LNOSRESEARCHER** [comment]
research

**Comment by bitcoinamerica** [comment]
is this that liquid you where talking about?

**Comment by LNOSRESEARCHER** [comment]
didnt know how to add it to library

**Comment by LNOSRESEARCHER** [comment]
yep

**Comment by LNOSRESEARCHER** [comment]
from what i heard was LN was for small transactions and liquid was for larger amounts of btc like exchanges/banks/financial institutions 
ALSO LIQUID WAS INSTANT NO WAIT for confirmation because each party has a financial obligation to one another

**Comment by LNOSRESEARCHER** [comment]
i check into the details but pretty sure its running now

**Comment by bitcoinamerica** [comment]
if its running it has not been supported or updated in 6 months and that's a long time for something to be in a beta

**Comment by LNOSRESEARCHER** [comment]
true

**Comment by bitcoinamerica** [comment]
Got a min watch this video if your not doing anything rely lesson when he talks about this happens to sync up reality's /alter-reality's !!
https://www.youtube.com/watch?v=8KFMFON4Np4

**Comment by bitcoinamerica** [comment]
Oh shit and on fox News last night they announced, that we are having visible radio burst that are said to have come from intelligent life from another part of the solar system

**Comment by LNOSRESEARCHER** [comment]
its called blockstream and liquid is used there

**Comment by LNOSRESEARCHER** [comment]
just another sidechain that was to be used for bakk

**Comment by bitcoinamerica** [comment]
shoot me the link and included info of what the link is so im not asking "he whats this" when you find it

**Comment by LNOSRESEARCHER** [comment]
you can have cold storage on liquid not on LN

**Comment by LNOSRESEARCHER** [comment]
FROM WHAT IM LISTING TO IS LIQUID TAKES UP TO 2 MIN AND LN IS INSTANT
AND LN WILL RIDE ON THE LIQUID NETWORK IN FUTURE  ( IN YOUTUBE VIDEO MARIO GIBNEY @BLOCKSTREAM) https://youtu.be/7Qc8kMqfomY

**Comment by bitcoinamerica** [comment]
the eclair "light" application act like a cold storage too.
but a 3rd party runs the node

i don't trust the code because this "side-chain" is not as secure as the bitcoin block chain, were the actual bitcoin block chain dose the work and eclair just keeps up with who money is who's. if that makes cent's . but liquid you take your coin info off the blockchain and give it to another blockchain that takes your coin and gives you a "token" called bitcoin...u decide i know my answer, that if i needed to move a large amount of bitcoin i would just use core

**Comment by LNOSRESEARCHER** [comment]
I AGREE i think it will be a time transfer issue as it can take a long time transfering btc on core

**Comment by LNOSRESEARCHER** [comment]
thats why if you dont have big money you wont be able to perticipate

**Comment by LNOSRESEARCHER** [comment]
could very well be..
 ill check it out tomorrow  im gone.. chow

**Comment by bitcoinamerica** [comment]
same

**Pull request closed without merging**
